---
kind: pipeline
type: docker
name: seasonedParser

platform:
  os: linux
  arch: amd64

steps:
- name: install-python3.6
  image: python:3.6-alpine
  commands:
    - pip install -r requirements.txt

- name: install-python3.8
  image: python:3.8-alpine
  commands:
    - pip install -r requirements.txt 

trigger:
  branch:
    - master
  event:
    include:
      - pull_request
      - push 

